server:
  port: 8087

  servlet:
    context-path: /api/chat
    encoding:
      charset: utf-8
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    org:
      jsoup: trace

spring:
  application:
    name: chat

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/backtoback?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ssafy
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true


  output.ansi.enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # create, update, none
    generate-ddl: false
    properties:
      hibernate:
        #        dialect:
        #        default_schema:
        format_sql: true
    defer-datasource-initialization: true


  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  mvc:
    log-request-details: true # request의 parameter 값 등을 log에서 못 보는 설정 해제

  kafka:
    bootstrap-servers: k8a708.p.ssafy.io:9092
    consumer:
      group-id: kafka-chat-group
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

#  servlet:
#    multipart:
#      maxFileSize: 10MB
#      max-request-size: 10MB

chat:
  kafka:
    topics:
      - chat.all.game.1
      - chat.all.game.2
      - chat.all.game.3
      - chat.all.game.4
      - chat.all.game.5
      - chat.team.1
      - chat.team.2
      - chat.team.3
      - chat.team.4
      - chat.team.5
      - chat.team.6
      - chat.team.7
      - chat.team.8
      - chat.team.9
      - chat.team.10


logging.level:
  #  org.apache: trace
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org:
    springframework:
      security: trace
      boot:
        autoconfigure:
          security: trace
      web: trace
      http: trace
      batch: trace
      jdbc.core.JdbcTemplate: debug
