server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      charset: utf-8
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: apigateway
  cloud:
    gateway:

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://k8a708.p.ssafy.io'
            #            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      routes:
        - id: auth
          uri: http://auth:8085
          predicates:
            - Path=/api/auth/**
        - id: business
          uri: http://business:8086/
          predicates:
            - Path=/api/business/**
        - id: chat
          uri: http://chat:8087/
          predicates:
            - Path=/api/chat/**
        - id: chat_log
          uri: http://chat_log:8088/
          predicates:
            - Path=/api/chat-log/**
        - id: cheer
          uri: http://cheer:8089/
          predicates:
            - Path=/api/cheer/**
        - id: media
          uri: http://k8a708.p.ssafy.io:8091/
          predicates:
            - Path=/api/media/**
        - id: member
          uri: http://member:8082/
          predicates:
            - Path=/api/member/**
        - id: point
          uri: http://point:8084/
          predicates:
            - Path=/api/point/**
