server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  refresh-token-name: refresh-token
  access-token-name: access-token
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN


spring:
  redis:
    host: localhost
    port: 6379
    password: ssafy
  main:
    allow-bean-definition-overriding: true
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: chat
          uri: http://localhost:8087/
          predicates:
            - Path=/api/chat/**
        - id: chat_sockjs_route
          uri: http://localhost:8087/
          predicates:
            - Path=/api/chat/ws-chat/**
        - id: business
          uri: http://localhost:8086/
          predicates:
            - Path=/business/**
        - id: member
          uri: http://localhost:8081/
          predicates:
            - Path=/member/login
            - Method=POST

        - id: member
          uri: http://localhost:8081/
          predicates:
            - Path=/member/signup
            - Method=POST