server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: chat
          uri: http://localhost:8087/
          predicates:
            - Path=/chat/**
        - id: chat_sockjs_route
          uri: http://localhost:8087/
          predicates:
            - Path=/ws-chat/**
        - id: business
          uri: http://localhost:8086/
          predicates:
            - Path=/business/**