server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  refresh-token-name: refresh-token
  access-token-name: access-token
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN


spring:
  redis:
    host: localhost
    port: 6379
    password: ssafy
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: chat
          uri: http://localhost:8087/
          predicates:
            - Path=/api/chat/**
        - id: chat_sockjs_route
          uri: http://localhost:8087/
          predicates:
            - Path=/api/chat/ws-chat/**
        - id: business
          uri: http://localhost:8086/
          predicates:
            - Path=/business/**

        - id: member
          uri: http://localhost:8082/
          predicates:
            - Path=/api/member/**

        - id: auth
          uri: http://localhost:8085
          predicates:
            - Path=/auth/reissue
            - Method=GET
          filters:
            - AuthorizationHeaderFilter