spring:
  config:
    activate:
      on-profile: local
  datasource:
    # local
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/backtoback?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ssafy

#    url: jdbc:mariadb://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root