spring:
  config:
    activate:
      on-profile: local
  datasource:
    # local
    url: jdbc:mysql://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://k8a708.p.ssafy.io:3306/backtoback?useUnicode=true&characterEncoding=utf-8
  #    username: btob
  #    password: backback

  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

  redis:
    host: localhost
    port: 6379

web.driver.path: C:/chromedriver_win32/chromedriver.exe
#    url: jdbc:mariadb://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root