server:
  port: 8086
  servlet:
    context-path: /business
    encoding:
      charset: utf-8
      enabled: true

eureka:
  client:
    register-with-eureka: false # true
    fetch-registry: false   #true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      jsoup: trace

spring:
  application:
    name: business
  profiles:
    default: local # 기본 환경을 local로
  datasource:
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  output.ansi.enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 대문자, 소분자 구분
    #    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        #        dialect:
        #        default_schema:
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
  mvc:
    log-request-details: true # request의 parameter 값 등을 log에서 못 보는 설정 해제
  redis:
    host: localhost
    port: 6379
  cloud:
    function:
      definition: consumer;producer
    stream:
      bindings:
        producer-out-0:
          producer:
            auto-startup: false
            poller:
              fixedDelay: 0
          destination: game-event
        consumer-in-0:
          destination: game-event
      kafka:
        binder:
          brokers: k8a708.p.ssafy.io:9092


#  servlet:
#    multipart:
#      maxFileSize: 10MB
#      max-request-size: 10MB

logging.level:
  #  org.apache: trace
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org:
    springframework:
      security: trace
      boot:
        autoconfigure:
          security: trace
      web: trace
      http: trace
