server:
  port: 8082
  servlet:
    context-path: /api/member

jwt:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  refresh-token-name: refresh-token
  access-token-name: access-token
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN


spring:
  application:
    name: member

  data:
    redis:
      host: localhost
      port: 6379
      password: ssafy

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    # develop 브랜치 용
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
    username: root
    #    password: ssafy
    password: root

    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: none

eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka





