server:
  port: 8088

  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      jsoup: trace

spring:
  application:
    name: chat_log

  cloud:
    function:
      definition: getGameCondition; #process;


    stream:
      pollable-source: pollableInput

      default-binder: kafka

      bindings:
        pollableInput-in-0:
          destination: chat-room-1
          group: pollable-group
          consumer:

            partitioned: false
        #            batch-mode: true


        getGameCondition-in-0:
          destination: game-condition
          group: group1 # 컨슈머 그룹
          content-type: application/json
          #          consumer:
          #            batch-mode: true #한꺼번에 가져오기
          #            partitioned: false
          #            instance-count: 1

          #        process-in-0:
          #          destination: test
          #          group: group2 # 컨슈머 그룹
          #          content-type: application/json


          #        process-out-0:
          #          destination: topic2
          #          producer:
          #            auto-startup: false
          #            poller:
          #              fixedDelay: 0


      #        pollableInput-in-0: #name of our custom channel
      #          group: pollable-group #kafka consumer group
      #          destination: chat-room-1 #setting kafka topic to read from


      kafka:
        binder:
          auto-create-topics: false # 바인더는 이미 구성된 주제에 의존합니다. 항목이 없으면 바인더가 시작되지 않습니다.
          brokers: localhost:9092


          #          replication-factor: 1

          consumer-properties:
            max:
              poll:
                records: 10000

            fetch.max.wait.ms: 5000

            auto.offset.reset: latest



        #        bindings:

        #          process-out-0:
        #            producer:
        #              configuration:
        #                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer




  datasource:
    # develop 브랜치 용
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
    #    username: root
    #    password: ssafy

    # ssafy 노트북 local 용
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
    #    username: root
    #    password: ssafy

    # 효진 노트북 local 용
    url: jdbc:mysql://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

    #추가
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true


  output.ansi.enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 대문자, 소분자 구분
    #    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        #        dialect:
        #        default_schema:
        format_sql: true
    defer-datasource-initialization: true


  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  mvc:
    log-request-details: true # request의 parameter 값 등을 log에서 못 보는 설정 해제

#  servlet:
#    multipart:
#      maxFileSize: 10MB
#      max-request-size: 10MB


logging.level:
  #  org.apache: trace
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org:
    springframework:
      core: trace
      #      beans: trace
      cloud.stream: trace
      cloud.stream.binder: trace
      messaging: trace

      security: trace

      boot:
        autoconfigure:
          security: trace
      web: trace

      http: trace
