spring:
  config:
    activate:
      on-profile: local
  datasource:
    # local
    url: jdbc:mysql://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mariadb://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
